basePath: /bookcabin
info:
  contact:
    email: elko.s.eppasa@mail.com
    name: Elko Sharhadi Eppasa
    url: https://github.com/elkoshar
  description: This service is to handle Flight Search and Aggregation API. For more
    detail, please visit https://github.com/elkoshar/bookcabin
  title: Flight Search and Aggregation API
  version: "0.1"
paths:
  /flight/search:
    get:
      consumes:
      - application/json
      description: SearchFlight handles request for searching flights
      parameters:
      - default: id
        description: accept language
        in: header
        name: Accept-Language
        required: true
        type: string
      - description: id of Book
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Search Flight
      tags:
      - Flight
swagger: "2.0"
